name: flutter_widget_watermark_example
description: Example app for flutter_widget_watermark
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_watermark:
    path: ../
  path_provider: ^2.1.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sample.png
